"""Kinematics calibration and Genesis FK/IK validation helpers."""

from ufactory.kinematics.calibration import (
    KinematicsCalibration,
    DEFAULT_KINEMATICS_SUFFIX_ENV,
    LITE6_KINEMATICS_MIN_SN_MODEL_CODE,
    XARM_KINEMATICS_MIN_SN_MODEL_CODE,
    build_calibrated_urdf,
    fetch_robot_sn_from_ip,
    find_kinematics_yaml,
    get_robot_sn,
    has_per_unit_kinematics_calibration,
    load_kinematics_yaml,
    load_kinematics_calibration,
    log_kinematics_sn_status,
    parse_sn_model_code,
    prepare_robot_model_for_verification,
    resolve_kinematics_suffix,
    resolve_kinematics_suffix_from_ip,
    robot_name_from_firmware,
    sn_matching_user_kinematics_yaml_exists,
    user_kinematics_yaml_exists,
    validate_kinematics_calibration_request,
)
from ufactory.kinematics.orientation import GRIPPER_DOWN_QUAT_XYZW, GRIPPER_DOWN_RPY_RAD
from ufactory.kinematics.tcp_offset import (
    pose_flange_to_tcp,
    pose_tcp_to_flange,
    read_tcp_offset,
)

__all__ = [
    "DEFAULT_KINEMATICS_SUFFIX_ENV",
    "GRIPPER_DOWN_QUAT_XYZW",
    "GRIPPER_DOWN_RPY_RAD",
    "LITE6_KINEMATICS_MIN_SN_MODEL_CODE",
    "XARM_KINEMATICS_MIN_SN_MODEL_CODE",
    "build_calibrated_urdf",
    "KinematicsCalibration",
    "fetch_robot_sn_from_ip",
    "find_kinematics_yaml",
    "get_robot_sn",
    "has_per_unit_kinematics_calibration",
    "load_kinematics_yaml",
    "load_kinematics_calibration",
    "log_kinematics_sn_status",
    "parse_sn_model_code",
    "pose_flange_to_tcp",
    "pose_tcp_to_flange",
    "prepare_robot_model_for_verification",
    "read_tcp_offset",
    "resolve_kinematics_suffix",
    "resolve_kinematics_suffix_from_ip",
    "robot_name_from_firmware",
    "sn_matching_user_kinematics_yaml_exists",
    "user_kinematics_yaml_exists",
    "validate_kinematics_calibration_request",
]
