"""Dynamics validation subpackage (probe / reference / analysis / report / cli / poses).

Public API surface re-exported here so ``from ufactory.dynamics import X`` works
for the symbols downstream code historically consumed from the
``dynamics_validation``/``dynamics_static_analysis`` modules (which are kept as thin back-compat re-export shims).
"""

from __future__ import annotations

from ufactory.dynamics.report import (
    ABS_ERR_LIMITS,
    L2_ERR_LIMIT,
    REL_ERR_LIMIT,
    REPORT_SCHEMA_VERSION,
    DynamicsRunConfig,
    DynamicsSample,
    GenesisDynamicsSample,
    SafePose,
    TorqueCompareResult,
    UrdfDynamicsIssue,
    ValidationStatus,
    array_or_nan,
    compare_report_records,
    dynamics_report_paths,
    has_sdk_torque,
    joint_torque_rows,
    make_run_config,
    minute_stamp,
    now_stamp,
    read_report_records,
    sanitize_report_identity,
    sha256_file,
    torque_summary,
    write_csv_report,
    write_jsonl_report,
)
from ufactory.dynamics.plot import torque_plot_layout, write_torque_plot
from ufactory.dynamics.reference import (
    DEFAULT_GRAVITY_VECTOR,
    PinocchioReference,
    armature_aligned_mass,
    load_reference_backend,
)
from ufactory.dynamics.analysis import (
    LAYER_L2A,
    LAYER_L2B,
    LAYER_L3A,
    LAYER_L3B,
    STATIC_LAYERS,
    StaticLayerResult,
    StaticPoseAnalysis,
    analyze_genesis_internal,
    analyze_mass_matrices,
    analyze_pd_vs_pinocchio,
    analyze_pin_vs_real,
    build_dynamics_sample,
    build_static_pose_analysis,
    classify_torque_result,
    compare_torques,
    estimate_pd_residual,
    format_torque_row,
    parse_strict_static_layers,
    pinocchio_static_at_q,
    static_layer_l2,
    summarize_static_layers,
    torque_result_from_sample,
    validate_urdf_dynamics,
)
from ufactory.dynamics.probe import (
    build_genesis_scene,
    capture_self_contacts,
    check_genesis_path_z,
    compute_ee_xyz_table_from_sim,
    compute_ee_z_table_from_sim,
    format_self_contacts,
    genesis_ee_z_mm_at_q,
    genesis_gravity_torque_at_q,
    genesis_pd_hold_torque_at_q,
    read_joint_frictionloss,
    resolve_entity_name,
    set_pd_gains,
    test_energy_dissipation,
    test_gravity_compensation_torques,
    test_gravity_freefall,
    test_mass_matrix_plausibility,
    test_mass_parameters,
    test_pd_step_response,
)
from ufactory.dynamics.poses import (
    DYNAMICS_EXTRA_CONFIGS,
    EE_LINK_NAME,
    JOINT_NAMES,
    PD_KP,
    PD_KV,
    FORCE_LOWER,
    FORCE_UPPER,
    URDF_JOINT_EFFORT,
    check_joint_limit_path,
    dynamics_default_configs,
    filter_safe_configs,
    merge_test_configs,
    parse_joint_limits,
    xarm6_default_dynamics_configs,
)
from ufactory.dynamics.poses_config import (
    default_configs_named_tuple,
    dynamics_pose_tuples,
    load_dynamics_pose_lists,
)

XARM6_DEFAULT_DYNAMICS_CONFIGS = dynamics_pose_tuples("xarm6", include_stress=False)
XARM6_STRESS_DYNAMICS_CONFIGS = dynamics_pose_tuples("xarm6", include_stress=True)[
    len(load_dynamics_pose_lists("xarm6")[0]) :
]

from ufactory.dynamics.cli import (
    SimCollisionResult,
    cli_hardware_check,
    cli_report_compare,
    cli_sim_check,
    cli_sim_collision_check,
    run_sim_collision_chain,
    write_sim_collision_report,
)

__all__ = [
    "ABS_ERR_LIMITS",
    "DYNAMICS_EXTRA_CONFIGS",
    "DEFAULT_GRAVITY_VECTOR",
    "DynamicsRunConfig",
    "DynamicsSample",
    "EE_LINK_NAME",
    "FORCE_LOWER",
    "FORCE_UPPER",
    "GenesisDynamicsSample",
    "JOINT_NAMES",
    "LAYER_L2A",
    "LAYER_L2B",
    "LAYER_L3A",
    "LAYER_L3B",
    "L2_ERR_LIMIT",
    "PD_KP",
    "PD_KV",
    "PinocchioReference",
    "REL_ERR_LIMIT",
    "REPORT_SCHEMA_VERSION",
    "STATIC_LAYERS",
    "SafePose",
    "SimCollisionResult",
    "StaticLayerResult",
    "StaticPoseAnalysis",
    "TorqueCompareResult",
    "URDF_JOINT_EFFORT",
    "UrdfDynamicsIssue",
    "ValidationStatus",
    "XARM6_DEFAULT_DYNAMICS_CONFIGS",
    "XARM6_STRESS_DYNAMICS_CONFIGS",
    "default_configs_named_tuple",
    "dynamics_pose_tuples",
    "load_dynamics_pose_lists",
    "analyze_genesis_internal",
    "analyze_mass_matrices",
    "analyze_pd_vs_pinocchio",
    "analyze_pin_vs_real",
    "armature_aligned_mass",
    "array_or_nan",
    "build_dynamics_sample",
    "build_genesis_scene",
    "build_static_pose_analysis",
    "capture_self_contacts",
    "check_genesis_path_z",
    "check_joint_limit_path",
    "classify_torque_result",
    "cli_hardware_check",
    "cli_report_compare",
    "cli_sim_check",
    "cli_sim_collision_check",
    "compare_report_records",
    "compare_torques",
    "compute_ee_xyz_table_from_sim",
    "compute_ee_z_table_from_sim",
    "dynamics_report_paths",
    "dynamics_default_configs",
    "estimate_pd_residual",
    "filter_safe_configs",
    "format_self_contacts",
    "format_torque_row",
    "genesis_ee_z_mm_at_q",
    "genesis_gravity_torque_at_q",
    "genesis_pd_hold_torque_at_q",
    "has_sdk_torque",
    "joint_torque_rows",
    "load_reference_backend",
    "make_run_config",
    "merge_test_configs",
    "minute_stamp",
    "now_stamp",
    "parse_joint_limits",
    "parse_strict_static_layers",
    "pinocchio_static_at_q",
    "read_joint_frictionloss",
    "read_report_records",
    "resolve_entity_name",
    "run_sim_collision_chain",
    "sanitize_report_identity",
    "set_pd_gains",
    "sha256_file",
    "static_layer_l2",
    "summarize_static_layers",
    "test_energy_dissipation",
    "test_gravity_compensation_torques",
    "test_gravity_freefall",
    "test_mass_matrix_plausibility",
    "test_mass_parameters",
    "test_pd_step_response",
    "torque_plot_layout",
    "torque_result_from_sample",
    "torque_summary",
    "validate_urdf_dynamics",
    "write_csv_report",
    "write_jsonl_report",
    "write_torque_plot",
    "write_sim_collision_report",
    "xarm6_default_dynamics_configs",
]
